### PR TITLE
Remove the [dup] tactic

### PR DESCRIPTION
**Pull request by soraros**

### CODE REVIEW

**Comment by lthms** [comment]
Dear @soraros, thanks for the pull request! I wasn’t aware of the existence `pose proof` (I really should take an afternoon and read the manual top to bottom). I wonder if `dup` is that useful, from this perspective.

**Comment by soraros** [comment]
@lthms Ok. So I removed it from the code base.

**Comment by lthms** [comment]
Thanks! I have taken the liberty to squash your commits and push them to `master`: https://github.com/ANSSI-FR/coq-prelude/commit/e1f86d3f81b60136986296e841be5c033dba5176.

Out of curiosity: have you a particular interest in `coq-prelude`? :)

**Comment by soraros** [comment]
I have limited knowledge to coq (and programming in general) so even if I'm interested in `coq-prelude` I don't think I can do more than some simple gardening. 😅
I was just trying to read the library trying to learn something about writing a std-ish library in coq.

**Comment by lthms** [comment]
I see. In this case, don’t hesitate to ask any question or feedback you might have!

**Pull request closed without merging**
